spring.application.name=Job-Portal
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb\://localhost\:27017/jobportal


#Email Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shshinde@mitaoe.ac.in
spring.mail.password=hmsoodxbxeqhwikm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true


USER_FOUND = User has registered already.
USER_NOT_FOUND = User is not registered.
INVALID_CREDENTIALS = Invalid credentials entered.
OTP_NOT_FOUND = OTP is expired.
OTP_INCORRECT = OTP is invalid.
JOB_NOT_FOUND= Job not found.
JOB_NOT_FOUND = Job applied already.
